### ISSUE TITLE
Requesting support for Folia

### ISSUE THREAD

**Issue by Q2297045667** [pop4959/BoltTowny#1]
Requesting support for Folia, https://github.com/PaperMC/Folia
I really like this plugin, so it's very important to me. Thank you

**Comment by pop4959** [comment]
Does Towny even have Folia support

**Comment by Momshroom** [comment]
It does since 0.99.5.0

**Comment by pop4959** [comment]
Thanks, saved me from digging. I'll see later if Folia support can easily be slapped on here. I can't imagine it'll be much if any work considering Bolt already supports it.

**Comment by pop4959** [comment]
Done, as expected no changes really needed here. BoltTowny only uses Bolt and Towny APIs, nothing that would directly affect compatibility with Folia. Just needed to mark as supported. New version is available on [Modrinth](https://modrinth.com/plugin/bolttowny).
